name: Hello World Workflow

on:
  push:
    branches:
      - main   # Runs when you push to main branch
  workflow_dispatch:  # Allows manual trigger from GitHub Actions tab

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, World!"
